apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    {{- include "dinspin.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secret.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secret.postgresDb | quote }}
  DATABASE_URL: "postgresql://{{ .Values.secret.postgresUser }}:{{ .Values.secret.postgresPassword }}@{{ .Release.Name }}-postgres:{{ .Values.postgres.port }}/{{ .Values.secret.postgresDb }}"
