apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    {{- include "dinspin.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      nodePort: {{ .Values.backend.nodePort }}
  type: NodePort
